Colm3na/polkastats-backend-v3

- README.md
Add steps to upload docker containers to new version.
> Update README.md with docker updating info

- docker/polkastats-backend/docker-compose.yml
- docker/polkastats-backend/wait-for-postgres.sh
- docker/polkastats-backend/wait-for-substrate-node.sh
- package.json
Looks nice but I tried changing the scripts names and it looks like it is not working.
I also don't see any outputs from the scripts during the building.
Can you try on your Linux machines the scripts separately? I was testing them here on Windows with the containers on and off but I'm afraid the Windows environment might be messing things a little bit up.
This is a work in progress. Need to really check into this.
> WIP: Ana/more docker improvements (wait for startup scripts)

- backend.config.js
- docker/polkastats-backend/backend/Dockerfile
Git clone develop branch of backend in docker, fix node hostname.
> Git clone develop branch of backend in docker

- crawlers/block-harvester.js
- crawlers/block-listener.js
> await api.isReady

- crawlers/block-harvester.js
- crawlers/block-listener.js
CLOSES #10 
Thanks to @Scriptonita we have addressed this!
> Crawlers should wait until node is synced

- crawlers/block-harvester.js
> Harvester now run backwards

- docker/polkastats-backend/README.md
CLOSES #27 
Backup and Restore scripts documented in dockers README.md
> Backup and Restore scripts documented in dockers README.md

- docker/polkastats-backend/docker-compose.yml
This PR adds the account crawler to docker-compose.yml
> New active accounts crawler service in docker compose

- crawlers/staking.js
- docker/polkastats-backend/sql/polkastats.sql
CLOSES #6 
Basic functionality is implemented.
> Staking crawler

- docker/polkastats-backend/docker-compose.yml
> add substrate node as compose dependence

- docker/polkastats-backend/clean-polkastats-dockers
- package.json
Just added new crawlers and improve the script.
> Add new crawlers to the script

- lib/BackendV3.js
- lib/crawlers/activeAccounts.js
- lib/crawlers/blockHarvester.js
- lib/crawlers/phragmen.js
- lib/utils.js
- Improved code for checking if the node is in syncing state.
- Added debug messages so we can understand what is happening.
> Improved code for checking if node is in syncing state

- docker/polkastats-backend/phragmen/Dockerfile
Compile offline-phragmen binary during docker image build
Closes #54
> Improve phragmem docker file

- backend.config.js
- docker/polkastats-backend/docker-compose.yml
- package.json
It needs to fix some paths for phragmen to work
> Add new service and fix some paths

- README.md
- docker/polkastats-backend/substrate-client/restore-backup
- docker/polkastats-backend/substrate-client/start-backup
This is the main documentation file. We will use this as deliverable for mileston 1.
It aims to build the entire laboratory we have develop until now.
> Update documentation and backup scripts

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Issue Number: N/A
This PR adds new PR and issue templates to our repository 
We need to put other developers in context when we need a code review for our PR.
It is not tested.
> Add new PR and issue templates

- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/staking.js
CLOSES #53 
Populate graph data tables to allow us to create cool charts for our future frontend v3.
> Save data for future validator graphs

- package-lock.json
- package.json
Closes #64
Update @polkadot/api to v1.6.2
Thank you! 🚀
---
For reviewer:
> Update @polkadot/api to v1.6.2

- docker/polkastats-backend/docker-compose.yml
Update Hasura docker image to latest stable version (1.1.0).
---
For reviewer:
> Update hasura image

- docker/polkastats-backend/substrate-client/Dockerfile
Closes #72
This just update the polkadot binary
Thank you! 🚀
---
For reviewer:
> Update polkadot daemon

- backend.config.js
- index.js
- lib/BackendV3.js
- lib/crawlers/activeAccounts.js
- lib/crawlers/blockHarvester.js
- lib/crawlers/blockListener.js
- lib/crawlers/phragmen.js
- lib/crawlers/rewards.js
- lib/crawlers/staking.js
Improve configuration to allow disabling some crawlers.
Also fix some calls to `setTimeout` where the argument is not a function.
---
For reviewer:
---
Closes #70
> Disable crawlers through config

- docker/polkastats-backend/docker-compose.yml
Closes #77 
Add restart on-failure flag to substrate-node and crawler services in docker-compose
Thank you! 🚀
---
For reviewer:
> Add restart on-failure flag to substrate-node and crawler services in docker-compose

- lib/BackendV3.js
Closes #79 
Adds a 15 sec delay to `runCrawlers()` function init.
Thank you! 🚀
---
For reviewer:
> Add startup delay to crawler

- package-lock.json
- package.json
Closes #85 
Update polkadot API to v1.7.1
Thank you! 🚀
---
For reviewer:
> Update polkadot API to v1.7.1

- docker/polkastats-backend/substrate-client/Dockerfile
Closes #87
Just update de substrate node
Thank you! 🚀
---
For reviewer:
> New v0.7.26 substrate node

- docker/polkastats-backend/backend/Dockerfile
Closes #76
Temporary disable the default and slow rust build process of phragmen binary.
Waiting for @Bigomby to accept the PR in his personal repo.
Thank you! 🚀
---
For reviewer:
> [WIP] Comment out the build process and download the binary

- package-lock.json
- package.json
Closes #89 
Tested and works awesome.
Thank you! 🚀
---
For reviewer:
> Upgrade @polkadot/api to v1.8.0-beta.2

- lib/crawlers/staking.js
Closes #92 
Refactor staking crawler: fix concurrency, intentions, era points, log messages and a bunch of other small things.
Thank you! 🚀
---
For reviewer:
> Refactor staking crawler

- backend.config.js
Closes #95 
Disable phragmen crawler as discussed.
Thank you! 🚀
---
For reviewer:
> Disable phragmen crawler

- backend.config.js
- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/activeAccounts.js
- lib/crawlers/staking.js
Closes #94 
Refactor accounts crawler
Thank you! 🚀
---
For reviewer:
> Refactor accounts crawler

- lib/crawlers/blockListener.js
Closes #98 
Fix duplicate key error in block listener.
Thank you! 🚀
---
For reviewer:
> Fix duplicate key error in block listener

- lib/crawlers/blockHarvester.js
Closes #90 
Refactor block harvester to adapt to recent kusama api/runtime changes.
Tested and working!
Thank you! 🚀
---
For reviewer:
> Fix block harvester

- README.md
- backend.config.js
- docker/polkastats-backend/docker-compose.yml
Closes #ISSUE
Use environment variable for WS_PROVIDER_URL in docker compose file and document it.
Thank you! 🚀
---
For reviewer:
> Use environment variable for WS_PROVIDER_URL

- docker/polkastats-backend/backend/Dockerfile
- docker/polkastats-backend/substrate-client/Dockerfile
- lib/crawlers/staking.js
- package-lock.json
- package.json
> Release Milestone1

- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/chain.js
- lib/crawlers/staking.js
- lib/crawlers/system.js
Closes #119 
Add intention bonded graph data
Thank you! 🚀
---
For reviewer:
> Add intention bonded graph data

- docker/polkastats-backend/substrate-client/Dockerfile
Needed update of substrate node.
> Upgrade to v0.7.30

- lib/crawlers/staking.js
Closes #128 
Add `currentElected` property to validator staking info
Thank you! 🚀
---
For reviewer:
> Add currentElected property to validator staking info

- lib/crawlers/staking.js
Closes #106 
Finally currentElected staking property.
Thank you! 🚀
---
For reviewer:
> Fix currentElected staking property

- docker/polkastats-backend/docker-compose.yml
- docker/polkastats-backend/substrate-client/Dockerfile
Closes #133 
Upgrade polkadot client to v0.7.32.
Add --unsafe-rpc-expose to node
Thank you! 🚀
---
For reviewer:
> WIP change version, add --unsafe-rpc-expose

- lib/crawlers/blockHarvester.js
- lib/crawlers/blockListener.js
- package-lock.json
- package.json
Closes #134 
Needed upgrade!
Thank you! 🚀
---
For reviewer:
> Upgrade polkadot api to v1.12.2

- docker/polkastats-backend/docker-compose.yml
- docker/polkastats-backend/substrate-client/Dockerfile
Closes #148 
Upgrade parity polkadot to 0.7.33
Thank you! 🚀
---
For reviewer:
> Upgrade parity polkadot to 0.7.33

- package-lock.json
- package.json
Closes #150 
Upgrade @polkadot/api to v1.13.1
Thank you! 🚀
---
For reviewer:
> Upgrade @polkadot/api to v1.13.1

- lib/crawlers/chain.js
Closes #152 
Fix bug in chain crawler
Thank you! 🚀
---
For reviewer:
> Fix bug in chain crawler

- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/blockHarvester.js
- lib/crawlers/blockListener.js
- lib/crawlers/staking.js
Closes #143 
Store validator produced blocks per session
Thank you! 🚀
---
For reviewer:
> Store validator produced blocks per session

- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/blockHarvester.js
- lib/crawlers/blockListener.js
- lib/utils.js
Closes #124 
**Goals:**
Thank you! 🚀
---
For reviewer:
> Store extrinsics

- lib/crawlers/rewardsSlashes.js
Refactor rewards and slashes crawler
Thank you! 🚀
---
For reviewer:
> Refactor rewards and slashes crawler

- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/activeAccounts.js
Closes #158 
Split account balances
Thank you! 🚀
---
For reviewer:
> Split account balances

- docker/polkastats-backend/sql/polkastats.sql
- lib/crawlers/activeAccounts.js
Add lockedBalance and identity display to accounts
Thank you! 🚀
---
For reviewer:
> Add lockeBalance and identity display to accounts

- docker/polkastats-backend/docker-compose.yml
- docker/polkastats-backend/substrate-client/Dockerfile
Closes #164 
Thank you! 🚀
---
For reviewer:
> Upgrade polkadot client to v0.8.1

- package-lock.json
- package.json
Closes #163 
Thank you! 🚀
---
For reviewer:
> Upgrade polkadot api

- docker/polkastats-backend/substrate-client/Dockerfile
Closes #168 
Thank you! 🚀
---
For reviewer:
> Upgrade polkadot node to v0.8.7

- package-lock.json
- package.json
Closes #170 
Thank you! 🚀
---
For reviewer:
> Upgrade polkadot api to v1.18.1
